Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.define "redhat" do |redhat|
    redhat.vm.box = "centos/7"
    redhat.vm.provision "ansible", verbose: "v", playbook: "test.yml", become: true
  end
end
